/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 ./public/hamburger.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva';

export default function Hamburger(props) {
  const { nodes, materials } = useGLTF('/hamburger.glb');

  const burger = useControls('Hamburger', {
    topBunWire: false,
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottomBun.geometry} material={materials.BunMaterial} material-wireframe={burger.topBunWire} />
      <mesh geometry={nodes.meat.geometry} material={materials.SteakMaterial} position={[0, 2.82, 0]} />
      <mesh geometry={nodes.cheese.geometry} material={materials.CheeseMaterial} position={[0, 3.04, 0]} />
      <mesh geometry={nodes.topBun.geometry} material={materials.BunMaterial} position={[0, 1.77, 0]} />
    </group>
  )
}

useGLTF.preload('/hamburger.glb')
